//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public College()
        {
            this.AttendedColleges = new HashSet<AttendedCollege>();
        }
    
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
    
        public virtual ICollection<AttendedCollege> AttendedColleges { get; set; }
    }
}
