//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrollment
    {
        public int EnrollmentID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public int EnrollmentStatus { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public bool ConditionalAdmission { get; set; }
        public bool TransferEquivalent { get; set; }
        public string Notes { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual EnrollmentStatusLookUp EnrollmentStatusLookUp { get; set; }
        public virtual Student Student { get; set; }
    }
}
