//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseEnrollments = new HashSet<CourseEnrollment>();
        }
    
        public int CourseID { get; set; }
        public string CourseNumber { get; set; }
        public string CourseItemNumber { get; set; }
        public string CourseName { get; set; }
        public int CourseTypeID { get; set; }
        public string CourseDescription { get; set; }
        public int Credits { get; set; }
        public bool RequiredForBASAdmission { get; set; }
        public bool RequiredForBASCompletion { get; set; }
        public int CreditSection { get; set; }
    
        public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; }
        public virtual CourseTypeLookUp CourseTypeLookUp { get; set; }
        public virtual CreditSectionLookUp CreditSectionLookUp { get; set; }
    }
}
