//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentStatusLookUp
    {
        public EmploymentStatusLookUp()
        {
            this.EmploymentStatus1 = new HashSet<EmploymentStatu>();
        }
    
        public int EmploymentStatusID { get; set; }
        public string EmploymentStatus { get; set; }
    
        public virtual ICollection<EmploymentStatu> EmploymentStatus1 { get; set; }
    }
}
