//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentStatu
    {
        public int EmploymentStatusID { get; set; }
        public int EmployerID { get; set; }
        public int StudentID { get; set; }
        public int Status { get; set; }
        public int JobTitleID { get; set; }
        public System.DateTime StatusChangedDate { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual EmploymentStatusLookUp EmploymentStatusLookUp { get; set; }
        public virtual JobTitleLookUp JobTitleLookUp { get; set; }
        public virtual Student Student { get; set; }
    }
}
