//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentStatusLookUp
    {
        public EnrollmentStatusLookUp()
        {
            this.CourseEnrollments = new HashSet<CourseEnrollment>();
        }
    
        public int EnrollmentStatusID { get; set; }
        public string EnrollmentStatus { get; set; }
    
        public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; }
    }
}
