//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int DetailID { get; set; }
        public int StudentID { get; set; }
        public int EduBackground { get; set; }
        public int ReferralType { get; set; }
        public int PreferredContactMethod { get; set; }
        public bool AttendedInfoSession { get; set; }
        public bool RunningStartParticipant { get; set; }
        public int BAS_Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Notes { get; set; }
    
        public virtual BAS_StatusLookup BAS_StatusLookup { get; set; }
        public virtual EduBackgroundLookup EduBackgroundLookup { get; set; }
        public virtual PreferredContactLookup PreferredContactLookup { get; set; }
        public virtual ReferralTypeLookup ReferralTypeLookup { get; set; }
        public virtual Student Student { get; set; }
    }
}
