//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.AttendedColleges = new HashSet<AttendedCollege>();
            this.CourseEnrollments = new HashSet<CourseEnrollment>();
            this.EmploymentStatus = new HashSet<EmploymentStatu>();
            this.StudentDetails = new HashSet<StudentDetail>();
        }

        public Student(int sid)
        {
            this.StudentID = sid;
            this.AttendedColleges = new HashSet<AttendedCollege>();
            this.CourseEnrollments = new HashSet<CourseEnrollment>();
            this.EmploymentStatus = new HashSet<EmploymentStatu>();
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public int StudentID { get; set; }
        public string RTCStudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string StudentEmail { get; set; }
        public string PersonalEmail { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool Gender { get; set; }
        public string Notes { get; set; }
        public string StudentDocumentsLocation { get; set; }
    
        public virtual ICollection<AttendedCollege> AttendedColleges { get; set; }
        public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; }
        public virtual ICollection<EmploymentStatu> EmploymentStatus { get; set; }
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
        public virtual TechInterest TechInterest { get; set; }
    }
}
