//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechInterest
    {
        public int StudentID { get; set; }
        public Nullable<bool> DatabaseDevelopment { get; set; }
        public Nullable<bool> SoftwareDevelopment { get; set; }
        public Nullable<bool> WebDevelopment { get; set; }
        public Nullable<bool> MobileDevelopment { get; set; }
        public Nullable<bool> DatabaseAnalysis { get; set; }
        public Nullable<bool> SoftwareAnalysis { get; set; }
        public Nullable<bool> InterfaceDesign { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
